kind: List
apiVersion: v1
items:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: rhcos-redirector
      app.kubernetes.io/component: rhcos-redirector
      app.kubernetes.io/instance: rhcos-redirector
    managedFields:
    - apiVersion: image.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/generated-by: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
        f:spec:
          f:tags:
            .: {}
            k:{"name":"latest"}:
              .: {}
              f:annotations:
                .: {}
                f:openshift.io/imported-from: {}
              f:from:
                .: {}
                f:kind: {}
                f:name: {}
              f:generation: {}
              f:importPolicy: {}
              f:name: {}
              f:referencePolicy:
                .: {}
                f:type: {}
      manager: oc
      operation: Update
    name: nginx-116
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.redhat.io/rhel8/nginx-116
      from:
        kind: DockerImage
        name: registry.redhat.io/rhel8/nginx-116
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: rhcos-redirector
      app.kubernetes.io/component: rhcos-redirector
      app.kubernetes.io/instance: rhcos-redirector
    managedFields:
    - apiVersion: image.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/generated-by: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
      manager: oc
      operation: Update
    name: rhcos-redirector
  spec:
    lookupPolicy:
      local: false

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: rhcos-redirector
      app.kubernetes.io/component: rhcos-redirector
      app.kubernetes.io/instance: rhcos-redirector
    managedFields:
    - apiVersion: build.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/generated-by: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
        f:spec:
          f:output:
            f:to:
              .: {}
              f:kind: {}
              f:name: {}
          f:runPolicy: {}
          f:source:
            f:git:
              .: {}
              f:uri: {}
            f:type: {}
          f:strategy:
            f:dockerStrategy:
              .: {}
              f:from:
                .: {}
                f:kind: {}
                f:name: {}
            f:type: {}
      manager: oc
      operation: Update
    - apiVersion: build.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:triggers: {}
        f:status:
          f:lastVersion: {}
      manager: openshift-apiserver
      operation: Update
    name: rhcos-redirector
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: rhcos-redirector:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/openshift-eng/rhcos-redirector
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nginx-116:latest
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 1
